feat: improve automated security tests

diff --git a/.gitlab/detect-secrets.gitlab-ci.yml b/.gitlab/detect-secrets.gitlab-ci.yml
--- a/.gitlab/detect-secrets.gitlab-ci.yml
+++ b/.gitlab/detect-secrets.gitlab-ci.yml
@@ -1,44 +1,49 @@
 ---
-# Job template - to be used in a pipeline by including this file.
+# SPDX-License-Identifier: GPL-3.0-or-later
+# (c) 2020-2024 Peter Mosmans [Go Forward]
 #
 # Detects secrets in modified files.
 #
+# Note that this tool expects the file BASELINE to be present in the root
+# directory. If not, the job will fail.
+#
 # Variables:
-# CONFIGURATION Directory where detect-secrets.json can be found
-# TOOLS_VERSION Specifies which version of gofwd/tools-image is being used
+# BASELINE          The baseline file of detect-secrets
+# TOOLS_VERSION     Specifies which version of gofwd/tools-image is being used
 
 detect-secrets:
   stage: .pre
-  image: gofwd/tools-image:$TOOLS_VERSION
+  image: gofwd/tools-image:${TOOLS_VERSION}
   variables:
     GIT_STRATEGY: clone
-    BASELINE: ${CONFIGURATION}/detect-secrets.json
-  script:
+    BASELINE: .secrets.baseline
+  before_script:
     - >
       if [[ ! -f "${BASELINE}" ]]; then
       echo "The file ${BASELINE} does not exist";
-      echo "Make sure to create and upload this first... exiting";
-      exit 1;
+      echo "Make sure to create and upload this first... exiting" ;
+      exit 1 ;
       fi
     - >
-      git config --global --add safe.directory ${CI_PROJECT_DIR};
-      git checkout ${CI_COMMIT_BRANCH};
-      mkdir -p reports &>/dev/null || true;
-      rm -rf reports/detect-secrets-report.txt &>/dev/null || true;
-      if [ "$CI_COMMIT_BEFORE_SHA" = "0000000000000000000000000000000000000000" ];
-      then
-      COMMIT_BEFORE_SHA=$(git rev-parse HEAD~1);
-      else
-      COMMIT_BEFORE_SHA=$CI_COMMIT_BEFORE_SHA;
-      fi;
-      echo "Checking files between ${COMMIT_BEFORE_SHA} and ${CI_COMMIT_BEFORE_SHA}"
-    - >-
-      echo "Checking the following files for secrets:
-      $(git diff --name-only --diff-filter=d $COMMIT_BEFORE_SHA $CI_COMMIT_SHA)"
+      git config --global --add safe.directory ${CI_PROJECT_DIR} ;
+      git checkout ${CI_COMMIT_BRANCH} ;
+      mkdir -p reports &>/dev/null || true
+  script:
     - >
+      if [ "$CI_COMMIT_BEFORE_SHA" = "0000000000000000000000000000000000000000" ] ;
+      then
+      COMMIT_BEFORE_SHA=$(git rev-parse HEAD~1) ;
+      else
+      COMMIT_BEFORE_SHA=$CI_COMMIT_BEFORE_SHA ;
+      fi;
+      echo "Checking files between ${COMMIT_BEFORE_SHA} and ${CI_COMMIT_BEFORE_SHA}" ;
+      echo "Checking the following files for secrets:
+      $(git diff --name-only --diff-filter=d $COMMIT_BEFORE_SHA $CI_COMMIT_SHA)" ;
       git diff --name-only --diff-filter=d $COMMIT_BEFORE_SHA $CI_COMMIT_SHA |
-      xargs detect-secrets-hook --baseline ${BASELINE} |
-      tee reports/detect-secrets-report.txt
+      xargs detect-secrets-hook --baseline ${BASELINE} > reports/detect-secrets-report.txt
+  # Always show report
+  after_script:
+    - cat reports/detect-secrets-report.txt
   artifacts:
     name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
     when: always
diff --git a/.gitlab/dockle.gitlab-ci.yml b/.gitlab/dockle.gitlab-ci.yml
--- a/.gitlab/dockle.gitlab-ci.yml
+++ b/.gitlab/dockle.gitlab-ci.yml
@@ -1,10 +1,11 @@
 ---
-# Job template - to be used in a pipeline by including this file.
+# SPDX-License-Identifier: GPL-3.0-or-later
+# (c) 2020-2024 Peter Mosmans [Go Forward]
 #
 # Lints a Docker image using Dockle.
+# Optional configuration will be read from .dockleignore
 #
 # Variables:
-# CONFIGURATION      Directory where .dockleignore can be found
 # DOCKLE_VERSION     Specifies which version of goodwithtech/dockle is being used
 # IMAGE_TAR          Name of the Docker image in tar format
 
@@ -19,21 +20,17 @@ dockle:
   image:
     name: goodwithtech/dockle:${DOCKLE_VERSION}
     entrypoint: [""]
+  before_script:
+    - mkdir -p reports &>/dev/null || true
   script:
-    - mkdir -p reports || true
-    # Check if the configuration directory exists and if so, execute from there
-    # This allows configuration files to be read
-    - >
-      if [[ -d "$CONFIGURATION" ]]; then
-      cd "${CONFIGURATION}" ;
-      dockle --input ../${IMAGE_TAR} --exit-code 1 |
-      tee ../reports/dockle-report.txt ;
-      else
-      dockle --input ${IMAGE_TAR} --exit-code 1 |
-      tee reports/dockle-report.txt ;
-      fi
+    - dockle --input ${IMAGE_TAR} --exit-code 1 > reports/dockle-report.txt
+  # Always show report
+  after_script:
+    - cat reports/dockle-report.txt
   artifacts:
+    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
     when: always
     paths:
-      - reports/dockle-report.txt
-
+      - reports/dockle-report.*
+  # Only flag the job as failed, not the whole pipeline
+  allow_failure: true
diff --git a/.gitlab/hadolint.gitlab-ci.yml b/.gitlab/hadolint.gitlab-ci.yml
--- a/.gitlab/hadolint.gitlab-ci.yml
+++ b/.gitlab/hadolint.gitlab-ci.yml
@@ -1,35 +1,30 @@
 ---
-# Job template - to be used in a pipeline by including this file.
+# SPDX-License-Identifier: GPL-3.0-or-later
+# (c) 2020-2024 Peter Mosmans [Go Forward]
 #
 # Lints a Dockerfile using hadolint.
+# Optional configuration will be read from .hadolint.yaml
 #
 # Variables:
-# CONFIGURATION      Directory where .hadolint.yaml can be found
 # HADOLINT_VERSION   Specifies which version of hadolint/hadolint is being used
 
 hadolint:
   extends: .sast
-  dependencies: []
-  variables:
-    GIT_DEPTH: 1
-    GIT_STRATEGY: fetch
   image:
     name: hadolint/hadolint:${HADOLINT_VERSION}
+  before_script:
+    - mkdir -p reports &>/dev/null || true
   script:
-    - mkdir -p reports || true
-    # Check if the configuration directory exists and if so, execute from there
-    # This allows the configuration file .hadolint.yaml to be read
     - >
-      if [[ -d "$CONFIGURATION" ]]; then
-      cd "${CONFIGURATION}" ;
-      hadolint ../Dockerfile -f sonarqube |
-      tee ../reports/hadolint-report.json ;
-      else
-      hadolint Dockerfile -f sonarqube |
-      tee reports/hadolint-report.json ;
-      fi
+      hadolint Dockerfile --no-fail > reports/hadolint-report.txt ;
+      hadolint Dockerfile --failure-threshold warning -f sonarqube > reports/hadolint-report.json
+  # Always show report
+  after_script:
+    - cat reports/hadolint-report.txt
   artifacts:
     name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
     when: always
     paths:
-      - reports/hadolint-report.json
+      - reports/hadolint-report.*
+  # Only flag the job as failed, not the whole pipeline
+  allow_failure: true
